# 项目配置
server:
  port: 9082
  servlet:
    context-path: /wechat

schedule:
  msg:
    receiver: filehelper
    text: '定时发送消息，防止掉线。'
  # 初始延迟配置
  initialDelayString:
    # 扫描预警结果任务延迟时间：1 秒
    send-msg: 1000
  # 定时周期配置（不阻塞）
  fixedRateString:
    # 测试定时器
    test: 5000
    # 扫描预警结果任务周期：20 分钟
    send-msg: 1200000

# spring
spring:
  security:
    user:
      name: admin
      password: 123456
  # 静态资源目录配置
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/

# 日志配置
logging:
  config: classpath:logback-spring.xml
